set block-policy drop
set skip on lo0

vip_ips = "{ 192.168.2.200, 192.168.2.201, 192.168.2.202 }"

# Redirecciones de portal
rdr pass on bridge100 inet proto {tcp udp} from any to any port 53 -> 192.168.2.1 port 53
rdr pass on bridge100 inet proto tcp      from any to any port 80 -> 192.168.2.1 port 8000

# Permisos mínimos (pasos rápidos antes del bloqueo)
pass quick on bridge100 inet proto udp from any port 68 to 255.255.255.255 port 67 keep state
pass quick on bridge100 inet proto {udp tcp} from any to 192.168.2.1 port 53 keep state
pass quick on bridge100 inet proto tcp from any to 192.168.2.1 port 8000 keep state
pass quick on bridge100 inet proto icmp from any to 192.168.2.1 keep state
pass quick on bridge100 inet from $vip_ips to any keep state  # opcional VIPs

# Bloqueo total del resto: evita que anchors de Internet Sharing/NAT de Apple hagan pass
block drop log quick on bridge100 from any to any

# Anchors de Apple (dejar al final)
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
